/**
 * Sample React Native App
 *
 * adapted from App.js generated by the following command:
 *
 * react-native init example
 *
 * https://github.com/facebook/react-native
 */

import React, { Component } from 'react';
import { StyleSheet, Text, View, TouchableOpacity } from 'react-native';
import Cardscan from 'react-native-cardscan';

export default class App extends Component {
  state = {
    status: 'starting',
  };
  async componentDidMount() {
    const isCompatible = await Cardscan.isCompatible();
    this.setState({
      status: isCompatible ? 'Cardscan is supported!' : 'Cardscan is not supported',
    });
  }
  render() {
    return (
      <View style={styles.container}>
        <Text style={styles.welcome}>☆Cardscan example☆</Text>
        <Text style={styles.instructions}>STATUS: {this.state.status}</Text>
        <TouchableOpacity
          onPress={async () => {
            const result = await Cardscan.scan();
            this.setState({ status: result.action });
          }}
        >
          <Text style={styles.welcome}>scan</Text>
        </TouchableOpacity>
      </View>
    );
  }
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: '#F5FCFF',
  },
  welcome: {
    fontSize: 20,
    textAlign: 'center',
    margin: 10,
  },
  instructions: {
    textAlign: 'center',
    color: '#333333',
    marginBottom: 5,
  },
});
