require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'
require_relative '../node_modules/react-native/scripts/react_native_pods'

platform :ios, '11.0'

target 'example' do
  pod 'CardScan', '~> 2.0.9'
  pod 'react-native-cardscan', :path => '../node_modules/react-native-cardscan'

  config = use_native_modules!
  use_react_native!(:path => config["reactNativePath"])
end

